pipeline {
  agent any
  tools {
    nodejs 'node_prod'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('SITH') {
      steps {
        build wait: false, job: 'parameterized', parameters: [text(name: 'SITH_ID', value: 'Vader-$BUILD_ID')]
      }
    }
  }
}
